<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="1" time="0.001"><testcase classname="test_FK.FK" name="test_zero_to_one" time="0.0007"><error type="UnboundLocalError">local variable 'output' referenced before assignment
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/marina/spot/src/tests/test_FK.py", line 33, in test_zero_to_one
    output = zero_to_one(A, length, width)
  File "/home/marina/spot/src/tests/FK.py", line 65, in zero_to_one
    return(output)
</error></testcase><system-out>&lt;![CDATA[

]]&gt;</system-out><system-err>&lt;![CDATA[
/home/marina/spot/src/tests/FK.py:44: RuntimeWarning: invalid value encountered in sqrt
  err = np.sqrt(length)
/home/marina/spot/src/tests/FK.py:45: RuntimeWarning: invalid value encountered in sqrt
  err = np.sqrt(width)

]]&gt;</system-err></testsuite>